### ISSUE TITLE
Full Size METRO 328 Schematic is missing for CP2104 variant

### ISSUE THREAD

**Issue by sciguy14** [adafruit/Adafruit-METRO-328-PCB#6]
Hello Adafruit folks! It would appear that only the FTDI variant of the full size METRO board schematic is present in this repo. Would you be willing to add the schematic (in eagle and/or PDF format) for the newer variant with the the CP2104 chip that you are now shipping?

Thanks!

**Comment by ladyada** [comment]
done!

**Comment by sciguy14** [comment]
I have submitted a pull request with a readability cleanup to the schematic you shared :)
(No functional changes of course)
https://github.com/adafruit/Adafruit-METRO-328-PCB/pull/7
